import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, History, FileDown, Calendar, AlertTriangle, ShieldCheck, Download, Loader2 } from 'lucide-react';
import { useAppContext } from '../context/AppContext';

function formatRisk(riskLevel) {
  switch (riskLevel) {
    case 'CRITICAL': return { color: '#FB7185', label: 'Critical Risk', bg: 'rgba(251,113,133,0.1)' };
    case 'HIGH':     return { color: '#FBBF24', label: 'High Risk',     bg: 'rgba(251,191,36,0.1)' };
    case 'MEDIUM':   return { color: '#818CF8', label: 'Medium Risk',   bg: 'rgba(129,140,248,0.1)' };
    default:         return { color: '#34D399', label: 'Low Risk',      bg: 'rgba(52,211,153,0.1)' };
  }
}

const AuditHistoryModal = ({ isOpen, onClose, theme }) => {
  const { auditHistory, clearAuditHistory } = useAppContext();
  const [downloadingIdx, setDownloadingIdx] = useState(null);

  const handleDownloadPDF = async (audit, idx) => {
    setDownloadingIdx(idx);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      
      const dateStr = new Date(audit.date).toLocaleDateString();
      const content = `EquiLens Bias Audit Report
Date: ${dateStr}
Dataset: ${audit.fileName || 'Unknown'}

--- EXECUTIVE SUMMARY ---
Risk Level: ${audit.riskLevel || 'Unknown'}
Demographic Parity Score: ${audit.parity || 'N/A'}/100
Fairness Score: ${audit.fairnessScore || 'N/A'}/10

Summary:
${audit.summary || 'No summary available.'}

--- KEY FINDINGS ---
${(audit.keyFindings || []).map(k => '- ' + k).join('\n')}

--- SUGGESTIONS ---
${(audit.suggestions || []).map(s => '- ' + s).join('\n')}

Generated by EquiLens AI.`;

      const cleanContent = content.replace(/[*#]/g, '').replace(/\n{3,}/g, '\n\n');
      const lines = doc.splitTextToSize(cleanContent, 180);
      doc.text(lines, 15, 15);
      doc.save(`EquiLens_Report_${dateStr.replace(/\//g, '-')}.pdf`);

    } catch (e) {
      console.error('Failed to generate PDF', e);
    } finally {
      setDownloadingIdx(null);
    }
  };

  if (!isOpen) return null;

  const isDark = theme !== 'light';

  return (
    <AnimatePresence>
      <div style={{
        position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 9999,
        background: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(0,0,0,0.2)',
        backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center'
      }}>
        <motion.div 
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="g-card"
          style={{
            width: '90%', maxWidth: 700, maxHeight: '85vh',
            background: isDark ? 'var(--bg-card)' : '#ffffff',
            display: 'flex', flexDirection: 'column', overflow: 'hidden',
            boxShadow: isDark ? '0 24px 60px rgba(0,0,0,0.4)' : '0 24px 60px rgba(0,0,0,0.1)'
          }}
        >
          {/* Header */}
          <div style={{
            padding: '20px 24px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            background: isDark ? 'rgba(0,0,0,0.2)' : 'var(--bg-card-2)'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <div style={{ padding: 8, borderRadius: 8, background: 'rgba(129,140,248,0.1)', color: '#818CF8' }}>
                <History size={20} />
              </div>
              <h2 style={{ fontSize: 18, fontWeight: 800, margin: 0, color: 'var(--text-1)' }}>Audit History</h2>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              {auditHistory && auditHistory.length > 0 && (
                <button onClick={clearAuditHistory} style={{
                  background: 'rgba(251,113,133,0.1)', border: '1px solid rgba(251,113,133,0.2)', color: '#FB7185', cursor: 'pointer', padding: '6px 12px', borderRadius: 6, fontSize: 11, fontWeight: 700, transition: 'all 0.2s', marginRight: 8
                }}
                >
                  Clear History
                </button>
              )}
              <button onClick={onClose} style={{
                background: 'transparent', border: 'none', color: 'var(--text-3)', cursor: 'pointer', padding: 8, borderRadius: 8
              }}>
                <X size={20} />
              </button>
            </div>
          </div>

          {/* Body */}
          <div style={{ padding: '24px', overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 16 }}>
            {(!auditHistory || auditHistory.length === 0) ? (
              <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-3)' }}>
                <History size={40} style={{ opacity: 0.2, margin: '0 auto 16px' }} />
                <p>No audit history found.</p>
                <p style={{ fontSize: 13 }}>Run your first bias audit to see history here.</p>
              </div>
            ) : (
              auditHistory.map((audit, idx) => {
                const rStyle = formatRisk(audit.riskLevel);
                const isDownloading = downloadingIdx === idx;
                
                return (
                  <div key={idx} style={{
                    padding: 20, borderRadius: 12, border: '1px solid var(--border)',
                    background: isDark ? 'var(--bg-card-2)' : 'var(--bg-page)'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                      <div>
                        <h4 style={{ margin: '0 0 6px 0', fontSize: 16, fontWeight: 700, color: 'var(--text-1)' }}>{audit.fileName || 'Unknown Dataset'}</h4>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 14, fontSize: 12, color: 'var(--text-3)' }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}><Calendar size={13} /> {new Date(audit.date).toLocaleString()}</span>
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: 12 }}>
                        <span style={{
                          padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 700,
                          background: rStyle.bg, color: rStyle.color, border: `1px solid ${rStyle.color}40`
                        }}>
                          {rStyle.label}
                        </span>
                      </div>
                    </div>

                    <p style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.6, margin: '0 0 16px 0' }}>
                      {audit.summary || 'Statistical analysis completed without narrative.'}
                    </p>

                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <div style={{ display: 'flex', gap: 16 }}>
                        <div style={{ display: 'flex', flexDirection: 'column' }}>
                          <span style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-3)' }}>Parity</span>
                          <span style={{ fontSize: 18, fontWeight: 800, color: '#34D399' }}>{audit.parity || 0}%</span>
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column' }}>
                          <span style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-3)' }}>Fairness</span>
                          <span style={{ fontSize: 18, fontWeight: 800, color: '#3B82F6' }}>{audit.fairnessScore || 0}/10</span>
                        </div>
                      </div>

                      <button 
                        onClick={() => handleDownloadPDF(audit, idx)}
                        disabled={isDownloading}
                        className="g-btn" 
                        style={{ padding: '8px 16px', fontSize: 13, gap: 8 }}
                      >
                        {isDownloading ? <Loader2 size={16} style={{ animation: 'spin-slow 1s linear infinite' }} /> : <FileDown size={16} />}
                        {isDownloading ? 'Generating...' : 'View Report (PDF)'}
                      </button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default AuditHistoryModal;
